apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  project: default # Change to the name of your ArgoCD project
  source:
    repoURL: 'https://github.com/coredns/helm.git'
    targetRevision: master
    path: charts/coredns
    #helm:
    #  valuesObject:
    plugin:
      name: kustomize-build-with-helm
      env:
        - name: HELM_VALUES
          value: |-
            customLabels:
              testing: "1234"
        - name: KUSTOMIZATION
          value: |-
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
              - all.yaml
            patchesJson6902:
              - target:
                  group: apps
                  version: v1
                  kind: Deployment # Adjust the kind if necessary
                  name: coredns-app-coredns
                patch: |-
                  - op: remove
                    path: /spec/selector/matchLabels/app.kubernetes.io~1instance
                  - op: remove
                    path: /spec/selector/matchLabels/app.kubernetes.io~1name
                  - op: add
                    path: /spec/selector/matchLabels/testing
                    value: "1234"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
